### PR TITLE
Corrected disk_type for raw disk mapping in vmware provider

### PR DESCRIPTION
**Pull request by hsong-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1720187

### CODE REVIEW

**Comment by hsong-rh** [comment]
@roliveri Please review.

**Comment by roliveri** [comment]
Hui, can you check into why codeclimate is failing?

**Comment by hsong-rh** [comment]
@roliveri The failure of codeclimate is an environment issue. It also fails in other repos.

**Comment by roliveri** [comment]
@hsong-rh I will let you know the new gem version.

**Comment by roliveri** [comment]
@hsong-rh The new VERSION = "0.2.24".

**Pull request merged**
