### PR TITLE
Add buildtime and url fields to collection from rpm database.

### PR DESCRIPTION
**Pull request by jeffmcutter**

### CODE REVIEW

**Comment by jeffmcutter** [comment]
Database schema changes required here:  https://github.com/ManageIQ/manageiq-schema/pull/417.

**Comment by jeffmcutter** [comment]
> Some comments on commits [jeffmcutter/manageiq-smartstate@cd1d67e~...6251779](https://github.com/jeffmcutter/manageiq-smartstate/compare/cd1d67ed62013cc012bd68cfa366b3f4f47bf93c~...625177929e240665533ba76ef882ed9f1e226696)
> 
> **lib/metadata/linux/MiqRpmPackages.rb**
> 
> * [ ]  warning - 155 - Detected `puts`. Remove all debugging statements.
> * [ ]  warning - 163 - Detected `puts`. Remove all debugging statements.

Follows existing code.

**Comment by jeffmcutter** [comment]
> Checked commits [jeffmcutter/manageiq-smartstate@cd1d67e~...6251779](https://github.com/jeffmcutter/manageiq-smartstate/compare/cd1d67ed62013cc012bd68cfa366b3f4f47bf93c~...625177929e240665533ba76ef882ed9f1e226696) with ruby 2.4.6, rubocop 0.69.0, haml-lint 0.20.0, and yamllint 1.10.0
> 2 files checked, 3 offenses detected
> 
> **lib/metadata/linux/LinuxPackages.rb**
> 
> * [ ]  exclamation - [Line 178](https://github.com/jeffmcutter/manageiq-smartstate/blob/625177929e240665533ba76ef882ed9f1e226696/lib/metadata/linux/LinuxPackages.rb#L178), Col 41 - [Style/BracesAroundHashParameters](http://rubydoc.info/gems/rubocop/0.69.0/RuboCop/Cop/Style/BracesAroundHashParameters) - Redundant curly braces around a hash parameter.
> 
> **lib/metadata/linux/MiqRpmPackages.rb**
> 
> * [ ]  exclamation - [Line 155](https://github.com/jeffmcutter/manageiq-smartstate/blob/625177929e240665533ba76ef882ed9f1e226696/lib/metadata/linux/MiqRpmPackages.rb#L155), Col 5 - [Rails/Output](http://rubydoc.info/gems/rubocop/0.69.0/RuboCop/Cop/Rails/Output) - Do not write to stdout. Use Rails's logger if you want to log.
> * [ ]  exclamation - [Line 163](https://github.com/jeffmcutter/manageiq-smartstate/blob/625177929e240665533ba76ef882ed9f1e226696/lib/metadata/linux/MiqRpmPackages.rb#L163), Col 5 - [Rails/Output](http://rubydoc.info/gems/rubocop/0.69.0/RuboCop/Cop/Rails/Output) - Do not write to stdout. Use Rails's logger if you want to log.

All of these issues follow existing style in the file.

**Comment by Fryguy** [comment]
@roliveri can you review?

**Pull request merged**
