### PR TITLE
Remove using ovirt gem

### PR DESCRIPTION
**Pull request by borod108**
There were still places using the ovirt gem that uses the V3 rhv api.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535782

### CODE REVIEW

**Comment by borod108** [comment]
@roliveri this is a blocker for the GA tomorrow, if we could get this merged it would be great.
@jerryk55 you were right, found those places in VmConfig :)

**Comment by roliveri** [comment]
@borod108 I'll post the new GEM version here once it's done.

**Comment by roliveri** [comment]
@borod108 New smartstate version = "0.3.1"

**Comment by borod108** [comment]
@roliveri thank you!
https://github.com/ManageIQ/manageiq/pull/19245

**Pull request merged**
