### PR TITLE
Revert switch to manageiq-password

### PR DESCRIPTION
**Pull request by agrare**
Depends on https://github.com/ManageIQ/manageiq-gems-pending/pull/408

### CODE REVIEW

**Comment by agrare** [comment]
@miq-bot assign @roliveri

**Comment by agrare** [comment]
@roliveri this is ready

**Comment by roliveri** [comment]
@agrare released version 0.2.17

**Comment by agrare** [comment]
:+1: thanks I'll bounce the last test on master

**Pull request merged**
