### PR TITLE
Reduce Complexity in LinuxMount.rb

### PR DESCRIPTION
**Pull request by jerryk55**
Based on Rubocop and CodeClimate scans
reduce the Cognitive and Cyclomatic Complexities.

@hsong-rh @roliveri please review and merge when appropriate.

### CODE REVIEW

**Comment by roliveri** [comment]
CodeClimate is still complaining.

**Comment by jerryk55** [comment]
@roliveri fixed more and pushed.  Lets see what it says.

**Comment by roliveri** [comment]
@jerryk55 
Negative progress.

**Comment by jerryk55** [comment]
Well not sure about that - I'm down from 5 CodeClimate issues to 1.  Plus the travis issue.

**Comment by roliveri** [comment]
I just meant the new travis issue. Didn't mean to make it sound like you were really making things worse - but it did sound that way, sorry.

**Comment by jerryk55** [comment]
The travis issue is strange.  Its complaining about the lines with the safe navigation operation with $log.debug.  I've used it in this way before successfully (I thought) but now its totally blowing up on any line using that in a log message (instead of checking "if $log.debug", which increases the complexity of a method.)

**Comment by jerryk55** [comment]
@roliveri @hsong-rh This is finally clean for both Travis and CodeClimate.  CodeClimate has moved this file from a "D" to an "A" with these changes.  I think it can be merged.

**Comment by jerryk55** [comment]
@miq-bot add_label smart-state

**Pull request merged**
