### PR TITLE
Remove Windows Platform Code

### PR DESCRIPTION
**Pull request by jerryk55**
All references to Windows Platform code have been removed, including
MiqLargeFileWin32 and references to it.
The original issue driving this PR is https://github.com/ManageIQ/manageiq/issues/1404 which was specific to Win32API being removed in Ruby 2.1.  However it seemed a waste of time to not also delete the other two minor places where a test for the Windows platform was made in this repo.

@djberg96 @Fryguy @roliveri please review.  Please merge when appropriate.  Thanks.

### CODE REVIEW

**Comment by djberg96** [comment]
Hm, something broke. And I guess Rubocop has some complaint.

**Comment by Fryguy** [comment]
Master is broken with the same issue (for like a month).  @jerryk55 can you fix master...I'm not sure how or I'd do it.

**Comment by chessbyte** [comment]
https://travis-ci.org/ManageIQ/manageiq-smartstate/builds shows that master has been broken for a month with the last green run being: https://travis-ci.org/ManageIQ/manageiq-smartstate/builds/242536677
@jerryk55 @roliveri @hsong-rh please fix so master is green again!

**Comment by roliveri** [comment]
@chessbyte @Fryguy - I haven't been able to find the disk image files needed to re-record the cassettes (to fix the maser build).

If there's no objection, I'll merge this, considering fixing the tests will take longer than expected.

**Comment by chessbyte** [comment]
@roliveri no objections.  same rationale applies for #13

**Pull request merged**
