### PR TITLE
Remove v3 api form SSA

### PR DESCRIPTION
**Pull request by borod108**
Remove the usage of the ovirt gem and version 3 api from the SSA

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535782

Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/394

### CODE REVIEW

**Comment by borod108** [comment]
@roliveri is this ok?

**Comment by borod108** [comment]
@miq-bot add_label bug
@miq-bot add_label ivanchuk/yes

**Comment by agrare** [comment]
@miq-bot assign @roliveri

**Comment by jerryk55** [comment]
I'm not sure this was looked at with regard to other interactions inside the SSA gem.  For instance, rhevmVm.disks was removed but it is used in the VmConfig code.

**Comment by roliveri** [comment]
@borod108,
as per Jerry's comment, are there still issues with the `VmConfig` code?

**Comment by borod108** [comment]
@jerryk55 can you suggest how I will find all those places? Currently with this code smartstate analysis works, how should I find all the places to change?

**Comment by agrare** [comment]
@borod108 could you maintain the same interface but use the v3 api instead?  That should fix the issue of having to find every caller

**Comment by borod108** [comment]
@agrare I could, we talked about it with Martin - it just does not seem to be a good solution. Also - if we fix it properly then the knowledge of how this thing actually works will spread to us as well and we will be able to fix things in the future and not keep putting bandages on this.

**Comment by borod108** [comment]
@agrare @roliveri @jerryk55 so how should we proceed?
Can you point me to what else I should change?
I mean it runs on my env and there are no tests for this part that fail so I am not sure what to do here...

**Comment by roliveri** [comment]
@jerryk55 Can you provide a pointer to where it's used in the `VmConfig` code?

**Comment by jerryk55** [comment]
Yeah let me look it up again.  Hopefully I'm not mistaken.  Or maybe its better if I am.  More to come....

**Comment by jerryk55** [comment]
I believe I was mistaken.  There is a reference to rhevmVm.disks in VMconfig - not rhevmVm.attributes[:disks] - I misread the code.  So I remove my objection to this.

**Comment by roliveri** [comment]
@borod108 Will release a new version of the manageiq-smartstate GEM and let you know the version.

**Comment by roliveri** [comment]
@borod108 released version 0.3.0 of the manageiq-smartstate GEM.

**Pull request merged**
