### PR TITLE
Add install_time field to collection for Windows packages.

### PR DESCRIPTION
**Pull request by jeffmcutter**

### CODE REVIEW

**Comment by Fryguy** [comment]
@roliveri Please review.

**Comment by jeffmcutter** [comment]
@Fryguy @roliveri 

Can you share your thoughts on this PR?

Thanks,
-Jeff

**Comment by Fryguy** [comment]
I like the change, but I'm mostly unfamiliar, and need @roliveri to weigh in.

**Comment by jeffmcutter** [comment]
Hi @roliveri,

No schema changes are required as install_time already exists for Linux SmartState packages.

Thanks,
-Jeff

**Comment by jeffmcutter** [comment]
Hi @roliveri,

If I recall correctly, the issues were a couple too many lines in the file (I added a handful) and one too many methods in the file (I added one).  Didn't seem serious to me, so I left.

Thoughts?

Thanks,
-Jeff

**Comment by roliveri** [comment]
@jeffmcutter OK, that should be fine.

**Comment by roliveri** [comment]
Released manageiq-smartstate 0.5.1

**Pull request merged**
